export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const FRIENDS_ROUTE = '/friends'
export const MAIN_ROUTE = '/'
export const NEWS_ROUTE = '/news'
export const DIALOGS_ROUTE = '/dialogs'
